import { AfterContentChecked, AfterViewInit, ChangeDetectorRef, ElementRef, EventEmitter, OnChanges, QueryList, SimpleChanges } from '@angular/core';
import { ADSStepPanelComponent } from '../step-panel/step-panel.component';
import { ADSStepComponent } from '../step/step.component';
import * as i0 from "@angular/core";
export declare class ADSStepperComponent implements AfterViewInit, AfterContentChecked, OnChanges {
    private readonly windowRef;
    private readonly cdr;
    stepper: ElementRef;
    css: string;
    step: number;
    readonly steppperChangeEmitter: EventEmitter<number>;
    steps: QueryList<ADSStepComponent>;
    panels: QueryList<ADSStepPanelComponent>;
    private stepButtonItems;
    private stepPanelItems;
    private selected;
    private focused;
    private readonly stepElementsChanged;
    constructor(windowRef: Window, cdr: ChangeDetectorRef);
    private focus;
    private select;
    private deselect;
    private setSizes;
    trackByIndex(index: number): number;
    ngAfterContentChecked(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngAfterViewInit(): void;
    private updateStepElements;
    static ɵfac: i0.ɵɵFactoryDeclaration<ADSStepperComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ADSStepperComponent, "ads-stepper", never, { "css": "css"; "step": "step"; }, { "steppperChangeEmitter": "steppperChangeEmitter"; }, ["steps", "panels"], never, false, never>;
}
