import { AfterViewInit, ChangeDetectorRef, ElementRef, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { Router } from '@angular/router';
import { IADSNavigation, IADSNavigationItem } from '../../types';
import * as i0 from "@angular/core";
export declare class ADSNavigationComponent implements OnChanges, AfterViewInit {
    private readonly document;
    private readonly router;
    private readonly cdr;
    nav: ElementRef;
    readonly clickEmitter: EventEmitter<Event>;
    appLink: string;
    autoExpand: boolean;
    navigation: IADSNavigation;
    labelToggle: string;
    labelClose: string;
    displayToggleButton: boolean;
    expandMainMenu: boolean;
    expandSubMenu: boolean;
    routerUrl: string;
    userPath: Array<IADSNavigationItem>;
    routerPath: Array<IADSNavigationItem>;
    constructor(document: Document, router: Router, cdr: ChangeDetectorRef);
    toggleMenu(): void;
    openMenu(): void;
    openSubMenu(): void;
    closeMenu(): void;
    focusCheck(target: Element, event?: KeyboardEvent | undefined): void;
    menuItemSelect(item: IADSNavigationItem, event: Event): void;
    moveOneLevelUp(event: Event): void;
    menuItemFocus(item: IADSNavigationItem): void;
    menuItemInUserPath(item: IADSNavigationItem): boolean;
    menuItemInRouterPath(item: IADSNavigationItem): boolean;
    menuItemHasChildren(item: IADSNavigationItem): boolean;
    menuItemHasVisibleSubmenu(item: IADSNavigationItem): boolean;
    parseRouteData(route: any): Record<any, any>;
    isFullUrl(url: string): boolean;
    checkRouterChange(event: any): void;
    clickEvent(): void;
    ngAfterViewInit(): void;
    trackByIndex(index: number): number;
    ngOnChanges(changes: SimpleChanges): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ADSNavigationComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ADSNavigationComponent, "ads-navigation", never, { "appLink": "appLink"; "autoExpand": "autoExpand"; "navigation": "navigation"; "labelToggle": "labelToggle"; "labelClose": "labelClose"; "displayToggleButton": "displayToggleButton"; }, { "clickEmitter": "clickEmitter"; }, never, never, false, never>;
}
